// Minimal Tauri Android stub used for JVM unit tests when the real Tauri Android SDK
// (.tauri/tauri-api, generated by tauri android build) is not present.
// Provides only the classes needed to compile AgeSignalsPlugin.kt.
plugins {
    kotlin("jvm") version "1.9.25"
}
